objects/Bypass_Logic_Switch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is created to toggle bypass logic for trigger, validation rule, flows etc.</description>
    <fields>
        <fullName>Bypass_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is utilized to bypass the trigger logic</description>
        <label>Bypass Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_To_Bypass__c</fullName>
        <description>This field going to hold the Object Name for which we want to bypass the trigger/validation rule/workflow</description>
        <label>Object To Bypass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bypass Logic Switch</label>
</CustomObject>

classes/Util.cls
/**
 * Class Name	:	Util
 * Created Date	:	29May2022
 * Created By	:	Chitresh Bhargava
 * Description	:	The Util class is a general purposed utility class using which we can reuse the existing block of code
 * 				  	without creating instance of the class.
 **/
public class Util {
    
    //Trigger Flag
    public static Boolean bypassTriggerForAllObjects = false;
    
    /**
     * Description	:	This method is created to bypass trigger for the respective object
     **/
    public static boolean bypassTriggerForSpecificObject(String objectName){
        
        //Varibale to hold boolean value
        Boolean bypassTrigger = false;
        
        //Get Bypass_Logic_Switch custom setting for the current user
        Bypass_Logic_Switch__c bypassLogicSwitch = Bypass_Logic_Switch__c.getInstance(UserInfo.getUserId());
        
        //Check Object Name is not blank or empty + Checkbox i.e. Bypass_Trigger is true + contains objectName or consider All Objects
        if(String.isNotBlank(bypassLogicSwitch.Object_To_Bypass__c) && bypassLogicSwitch.Bypass_Trigger__c == true
           && (bypassLogicSwitch.Object_To_Bypass__c.contains(objectName)
               || bypassLogicSwitch.Object_To_Bypass__c.equalsIgnoreCase('All'))
          )
        {
            bypassTrigger = true;
        }
        
        return bypassTrigger;
        
    }

}